# Manipulation de données en python avec Numpy



## Construction simple et attributs des tableaux numpy

On peut construire un tableau sous forme de liste de listes

In [6]:
import numpy as np

m=[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
print(type(m))
print(m)

<class 'list'>
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]


Convertissons cette structure en tableau numpy et regardons d'autres d'attributs de ce tableau

In [7]:
mat = np.array(m)
print(type(mat))
print(mat)

<class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [8]:
print(mat.ndim) # nombre de dimensions
print(mat.shape) # dimensions
print(mat.size) # nombre d'éléments
print(mat.itemsize) # taille d'un élément (en octets, 1 octet=8 bits)
print(mat.dtype) # type d'élément 64bits
print(mat.nbytes) # taille totale du tableau (en octets)

2
(4, 5)
20
8
int64
160


Occupation mémoire pour un tableau de chaînes : alignement sur la plus longue chaîne pour assurer une uniformité de la place prise par chaque objet.

In [10]:
prenoms = np.array(['alice','bob', 'charles', 'david', 'lisa'])
print(prenoms.nbytes)
print(prenoms.itemsize)  # 4 octets par lettre

140
28


On peut représenter chaque objet sur moins de bits (avec une moindre précision)

In [13]:
# conversion de type de tableau

tab1 = np.array([-2.7, 8.45, -0.89, 210, -675])
print(tab1.astype(np.int8))  # signé
print(tab1.astype(np.uint8)) # non signé

[ -2   8   0 -46  93]
[254   8   0 210  93]


On en profite pour croiser les outils python pour mesurer le temps d'execution

In [ ]:
# créer des tableaux de zeros, ones, empty, uint8 vs double

% timeit np.empty(shape=(1000, 1000), dtype=np.uint8)
% timeit np.zeros(shape=(1000, 1000), dtype=np.uint8)
% timeit np.ones(shape=(1000, 1000), dtype=np.uint8)
% timeit np.zeros(shape=(1000, 1000), dtype=np.double)

The slowest run took 38.90 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.08 µs per loop
The slowest run took 4.99 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 129 µs per loop
The slowest run took 6.32 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 139 µs per loop
The slowest run took 5.16 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 578 µs per loop


In [14]:
# Création de vecteur avec espacement régulier

print(np.arange(10))
print(np.arange(1,10))
print(np.arange(10,1,-1))
print(np.arange(1,3,0.2))
print(np.linspace(0,2*np.pi,10)) # aller de 0 à 2pi en 10 valeurs bornes incluses (l'espacement est calculé automatiquement)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [18]:
m=np.arange(12)
print("reshape:",m.reshape(3,4)) # renvoie le tableau modifié, ne modifie pas m
print("m=",m) #
print("reshape:",m.reshape(3,-1)) # "-1" va être remplacé automatiquement par la bonne valeur
print("resize:",m.resize(3,4))  # modifie m en place
print("m=",m)

reshape: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
m= [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
resize: None
m= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
m = np.array([[1, 2, 3], [4, 5, 6]])

# parcourir le tableau 2D : chaque passage extrait une ligne
for x in m:
  print(x)

# parcourir le tableau 2D : chaque passage extrait un élément
for x in np.nditer(m):
  print(x)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


## Vectorisation

In [23]:
x=np.linspace(0, 2*np.pi,10)

#exemple1 : application d'une fonction (fournie par la librairie) sur un vecteur
%timeit y=[np.sin(i) for i in x]  # c'est une boucle for déroulée
%timeit y=np.sin(x)  # beaucoup plus rapide car vectorisé

#exemple2 : application d'un opérateur sur un vecteur
x=np.array([1,-1,1,-1,1,-1,1,-1])
y=x>0  # le test est vectorisé
print(y)


12.4 µs ± 3.05 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
848 ns ± 202 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[ True False  True False  True False  True False]


In [ ]:
# exemple3 : application d'une fonction (fabriquée par nous et non fournie par une librairie) sur un vecteur

def cos_x2(x):
  return np.cos(x*x)

x=np.linspace(0, 2*np.pi,10)
z=cos_x2(x)

print(x)
print(z)


[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[ 1.          0.88355918 -0.36976414 -0.32015978  0.05574677  0.92804248
  0.26403549  0.31462428  0.97521564 -0.20700185]


In [24]:
#
x=np.linspace(0,2*np.pi,10)
# définition par morceaux: liste de conditions, liste de valeurs correspondantes pour la fonction
y=np.piecewise(x, [x < np.pi, x >= np.pi], [-1, 1])
print(y)

[-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]


In [25]:
x=np.array([1,-1,1,-1,1,-1,1,-1])

def my_absolute(tab):
    if tab < 0:  #ambiguité sur l'interprétation du "if" : quel sens sur un tableau de booléens ?
        return -tab
    else:
        return tab

%timeit my_absolute(x) # : ne marche pas, la fonction ne sait pas interpréter l'usage du tableau



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
from numba import jit #Jit : Numba Compilateur python Just-In-Time pour produire du code machine rapide d'execution
import random

# Ici la fonction en version qu'on va compiler

@jit(nopython=True)
def monte_carlo_pi_jit(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return(4.0 * acc / nsamples)

# Ici la fonction en version normale (executé en mode python interprété... lent !)

def monte_carlo_pi_normal(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return(4.0 * acc / nsamples)


%timeit monte_carlo_pi_jit(1000)
%timeit monte_carlo_pi_normal(1000)

14.8 µs ± 2.87 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
451 µs ± 6.62 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Indexation, slicing

In [30]:
 # Indexing, slicing

m=np.arange(0,12)
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [33]:
print(m[2:8])  #debut:fin (attention indice de fin+1)
print(m[2:-2:1])  #debut:fin:step  où fin: si négatif, à décompter depuis la fin du tableau

[2 3 4 5 6 7]
[2 3 4 5 6 7 8 9]


In [34]:
print(m[:-1:2]) #implicitement depuis le début du tableau
print(m[1:])  #implicitement jusqu'à la fin du tableau
print(m[::-1]) # step -1: parcourir le tableau à l'envers, implicitement depuis la fin jusqu'au début

[ 0  2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10 11]
[11 10  9  8  7  6  5  4  3  2  1  0]


In [36]:
# slicing en 2D

m=np.arange(0,36).reshape(6,6)
print(m)
print("---")
print(m[2:4,3:6]) # prendre un sous-tableau du tableau (indiquer intervalles de lignes puis colonnes)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
---
[[15 16 17]
 [21 22 23]]


In [37]:
lignes, colonnes = np.indices((3,3)) # comment récupérer l'ensemble des indices des cases si on veut en faire quelque chose
print(lignes)
print("---")
print(colonnes)

[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [ ]:
# slicing : crée des vues et non des copies, donc ça modifie en place !

m=np.arange(0,36).reshape(6,6)
print(m)
r=m[2:4,3:6] # r est une vue vers une partie de la zone mémoire contenant m
print(m.base is r.base) #True si m est une vue sur la mémoire de r, False m a sa propre zone mémoire
r[:,:]=-r  # on rend négatives toutes les valeurs de r
print(r)
print(m) # a aussi été modifié !


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
True
[[-15 -16 -17]
 [-21 -22 -23]]
[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14 -15 -16 -17]
 [ 18  19  20 -21 -22 -23]
 [ 24  25  26  27  28  29]
 [ 30  31  32  33  34  35]]


## Broadcasting

In [43]:
a=np.arange(5)
print(a)
print(a+2) #l'opérateur diffuse le +2 à tout le tableau au lieu de se plaindre d'incompatiblité de dimensions; pas besoin de créer un vecteur de "2"


[0 1 2 3 4]
[2 3 4 5 6]


In [ ]:
# même chose mais en dimension 2

m=np.arange(36).reshape(6,6)
print(m+2) #ajout d'une constant à une matrice

dim 2
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]
 [26 27 28 29 30 31]
 [32 33 34 35 36 37]]


In [44]:
m=np.arange(36).reshape(6,6) # tableau 6x6 qui va de 0 à 35
nh=np.arange(6) # tableau d'une ligne qui va de 0 à 5
nv=np.arange(6).reshape(6,1) # tableau d'une colonne qui va de 0 à 5
print(m)
print("---")
print(m+nh) # ajout d'une ligne à une matrice : ça l'ajoute à chaque ligne de la matrice
print("---")
print(m+nv)  # ajout d'une colonne à une matrice : ça l'ajoute à chaque colonne de la matrice

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
---
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]
 [24 26 28 30 32 34]
 [30 32 34 36 38 40]]
---
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]
 [28 29 30 31 32 33]
 [35 36 37 38 39 40]]


## Agrégation

In [ ]:

m=np.arange(6)
print(np.sum(m)) # la somme du vecteur
print(np.cumsum(m)) # le vecteur de somme cumulée

m=np.array([0,1,3,3,2,2,0,1])
print(np.argmax(m)) # la position du (premier) maximum
print(np.argwhere(m==np.max(m))) # la position de tous les maxima
print(np.all(m<5)) # test si tous les éléments du tableau remplissent une condition
print(np.any(m==1)) # test si au moins un élément du tableau léments remplissent une condition


15
[ 0  1  3  6 10 15]
2
[[2]
 [3]]
True
True


In [45]:
m=np.arange(36).reshape(6,6)
print(m)
print(m.max())  # le maximum sur tout le tableau
print(m.max(axis=0)) # le maximum par colonne
print(m.max(axis=1)) # le maximum par ligne

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
35
[30 31 32 33 34 35]
[ 5 11 17 23 29 35]


In [49]:
m=np.arange(36).reshape(6,6)
n=m[(m>20) & (m<32)] # exemple de récupération de sous-partie tableau, selon conditions
print(n)
print(np.count_nonzero((m>20) & (m<35)))  # comme son nom l'indique, nonzero inclus "non false"

[21 22 23 24 25 26 27 28 29 30 31]
14


In [ ]:
# Exemple : création de vue sur critère de sélection plutôt que bornes fixes

b = np.arange(1, 13).reshape(3, 4)
print(b)
view_index = np.nonzero(b%3==0)  # renvoie les indices des éléments du tableaux multiples de 3
print(view_index) # lire indice de ligne, indice de colonne
# comme b est de dimension 2,
# view_index est un tuple de 2 ndarray
view_index
b[view_index] # on peut maintenant venir modifier le tableau sur certains indices (là où il y avait un multiple de 3)
b[view_index] = b[view_index] * 10
b


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(array([0, 1, 2, 2]), array([2, 1, 0, 3]))


array([[  1,   2,  30,   4],
       [  5,  60,   7,   8],
       [ 90,  10,  11, 120]])

In [ ]:
# ensembles

a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices = np.unique(a, return_inverse=True)
print(u) # Les différentes valeurs présente dans leur tableau : maintenant c'est un ensemble
print(indices) # Pour chaque élément du tableau, son indice dans le tableau des valeurs possibles
print(u[indices]) # On peut reconstruire le tableau ainsi

[1 2 3 4 6]
[0 1 4 3 1 2 1]
[1 2 6 4 2 3 2]


In [ ]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
print(np.isin(5,a)) #test si un élément est dans un tableau
print(np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])) # Intersection entre deux tableaux (chaque élément n'est présent qu'une fois)
print(np.union1d([1, 3, 4, 3], [3, 1, 2, 1])) # Union entre deux tableaux (chaque élément n'est présent qu'une fois)

False
[1 3]
[1 2 3 4]


In [57]:
# passer une fonction à appliquer par ligne ou par colonne

a = np.arange(0, 9).reshape(3, 3)
print(a)

def diff_max_min(arr): # exemple: fonction qui renvoie la différence entre le max et le min d'un tableau arr
  return (max(arr)-min(arr))
print("---")
print(np.apply_along_axis(diff_max_min, 0,a)) # par colonne
print("---")
print(np.apply_along_axis(diff_max_min, 1,a)) # par ligne
print("---")
# Fait la même chose que juste avant mais où on se dispense de faire une fonction explicite
print(np.apply_along_axis(lambda arr: max(arr)-min(arr),1,a))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
---
[6 6 6]
---
[2 2 2]
---
[2 2 2]


In [58]:
a = np.arange(9)
print(a)
np.random.shuffle(a) #permutation aléatoire
print(a)

[0 1 2 3 4 5 6 7 8]
[5 8 3 2 1 6 4 7 0]


## agrégation de matrices

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.vstack((arr1, arr2))) #agréger deux matrices verticalement
print(np.hstack((arr1, arr2))) #agréger deux matrices horizontalement

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## calcul entre vecteurs et entre matrices

In [54]:
u=np.array([3,3])

print( np.inner( u,u.transpose() ) )  # produit scalaire (inner product)

18


In [52]:
print( np.outer( u.transpose(),u ) )  # produit externe (outer product)

[[9 9]
 [9 9]]


In [55]:
A=np.array([[1,2],[3,4]])
print( A @ u)  # notons que u est utilisé dans le sens colonne

[ 9 21]


In [56]:
print( u @ A)  # notons que u est utilisé dans le sens ligne

[12 18]
